### ISSUE TITLE
Write tests for database_mutation_functions.dart

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa#2144]
The Talawa code base needs to be 100% reliable. This means we need to have 100% unittest code coverage. No functionality must be removed to achieve this goal.

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
lib/services/database_mutation_functions.dart
```

The current code coverage for this file can be found here:
-  https://app.codecov.io/gh/PalisadoesFoundation/talawa?displayType=list

**Comment by Cioppolo14** [comment]
@imshivam-gupta  Would you still like this issue once one of your other issues is completed?

**Comment by imshivam-gupta** [comment]
Yes Sure @Cioppolo14

**Comment by imshivam-gupta** [comment]
@Cioppolo14 Can you assign me this issue. Since I have already created a PR for one issue and the other issue is solved already because the coverage was 99%. Both of these will be closed as soon as maintainers check the pr and issue thread.

**Comment by imshivam-gupta** [comment]
@Kevoniat You can close this issue since this issue is duplicate and already closed.

**Comment by Dante291** [comment]
duplicate issue of this issue is closed already, this file has 5.5% coverage and needed to be covered.

**Comment by Cioppolo14** [comment]
@imshivam-gupta This issue still needs to be completed, @Dante291 is correct it only had 5.5% coverage.

**Comment by imshivam-gupta** [comment]
Ok I got it @Cioppolo14. I will start working on it as soon as i finish other 2 issues.

**Comment by imshivam-gupta** [comment]
@Cioppolo14 Can you assign this issue to me?
