### ISSUE TITLE
Profile images missing for 'Liked by' and 'Comment' users.

### ISSUE THREAD

**Issue by bhoomikshetty** [PalisadoesFoundation/talawa#2279]
**Describe the bug**
Profile Images of users who have liked and commented is not visible.

**To Reproduce**

1. Open Individual Post screen
2. Like and Comment on the post.
3. Look at the profile images.

**Expected behavior**
Users respective profile images should be fetched and displayed in these places.

**Actual behavior**
Currently, there are blank circular avatars instead profile image.

**Screenshots**
![talawa-issue-comment-image (1)](https://github.com/PalisadoesFoundation/talawa/assets/76581406/30b34558-df75-414a-bf41-05b75f29b5f9)

**Comment by Shubhang001** [comment]
I wanted to work on this issue, could you please assign this to me?

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Abhisheksainii** [comment]
Can someone assign this issue to me?

**Comment by Abhisheksainii** [comment]
Issue has been resolved. I will raise the PR after testing the flow

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Mihan786Chistie** [comment]
@palisadoes I would like to try solving the issue

**Comment by YuanhuiAtGit** [comment]
Hi, does the issue still exist? If so, I'd like to be assigned.

**Comment by Cioppolo14** [comment]
Unassigning due to no activity

**Comment by GlenDsza** [comment]
@Cioppolo14 would like to work on this issue

**Comment by Cioppolo14** [comment]
@GlenDsza Because of your unique situation with the issues, I will assign this one to you. Thank you for letting me know.

**Comment by SumitPareek2401** [comment]
@Cioppolo14 can you please assign this issue to me?

**Comment by SumitPareek2401** [comment]
I am Unassigning this task.

**Comment by Dante291** [comment]
I would like to work on this @Cioppolo14

**Comment by Cioppolo14** [comment]
unassigning due to no pr or activity

**Comment by Dante291** [comment]
@Cioppolo14 I am in touch with backend developers for this issue as I am unable to fetch User's Image in a particular query, I am still working on this please assign me again.

**Comment by Dante291** [comment]
https://github.com/PalisadoesFoundation/talawa-api/issues/2262

This issue need to be fixed from API first then I will be able to fix this one.

**Comment by ayushnegi369** [comment]
can i also have a look on the issue, i would like to contribute to it so please assign it to me

**Comment by palisadoes** [comment]
> https://github.com/PalisadoesFoundation/talawa-api/issues/2262
> 
> This issue need to be fixed from API first then I will be able to fix this one.

The person unassigned themselves from the issue. You may have to work on it yourself

**Comment by Dante291** [comment]
@Cioppolo14 since im not that proficient in backed i have @AVtheking to work on it

**Comment by palisadoes** [comment]
@AVtheking can you work on this? It'll need to be assigned to you

**Comment by AVtheking** [comment]
Okay I will work on this assign it to me.

**Comment by palisadoes** [comment]
unassigning. inactivity

**Comment by aikansh008** [comment]
Hello sir, can you please assign this issue to me

**Comment by aikansh008** [comment]
hello sir sorry for late i was busy in my exams can you reassign this to me

**Comment by 3SyedShayan** [comment]
Hey, can this Issue be assigned to me, I am willing to work and solve this bug!

**Comment by palisadoes** [comment]
Unassigned. Inactivity

**Comment by harikrishna-au** [comment]
@palisadoes, is this still open to be resolved?
